version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: miniyape_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secure_miniyape_password"
      MYSQL_DATABASE: miniyape_db
      MYSQL_USER: user_miniyape
      MYSQL_PASSWORD: "secure_miniyape_password"
    volumes:
      # Volumen Ãºnico para los datos de este proyecto
      - miniyape_data:/var/lib/mysql

volumes:
  miniyape_data: